{% set name = "andes" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e55ce64c79fb04042304e19815ed060bd9393f30721bfda1c4f41f21989bf93

build:
  number: 0
  noarch: python
  entry_points:
    - andes = andes.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - coloredlogs
    - cvxopt >=1.2.3
    - dill
    - matplotlib-base
    - numpy
    - pandas
    - pathos
    - pyyaml
    - scipy
    - sympy
    - tqdm
    - xlrd ==1.2
    - openpyxl
    - xlsxwriter
    - chardet
    - numba

test:
  imports:
    - andes
    - andes.core
  commands:
    - pip check
    - andes selftest
  requires:
    - pip


about:
  home: https://github.com/cuihantao/andes
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Python Software for Symbolic Power System Modeling and Numerical Analysis
  doc_url: https://andes.readthedocs.io
  dev_url: https://github.com/cuihantao/andes
  description: |
    ANDES is a Python Software for Symbolic Power System Modeling and Numerical Analysis.
    Check out the introduction in the GitHub repository and documentation.

extra:
  recipe-maintainers:
    - cuihantao
