{% set name = "andes" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f020c784bbaeb73780fafa5b739c6ab608c2ff0ddc86e755e9f3f726d9250afb

build:
  number: 0
  entry_points:
    - andes = andes.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dill
    - cvxopt
    - numpy
    - scipy
    - sympy
    - pandas
    - xlrd
    - xlsxwriter
    - tqdm
    - pathos
    - pyyaml
    - coloredlogs
    - matplotlib-base

test:
  imports:
    - andes
  requires:
    - pytest
  commands:
    - andes

about:
  home: https://github.com/cuihantao/andes
  license: GNU General Public v3+
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A Python package for power system symbolic modeling and numerical simulation
  doc_url: https://andes.readthedocs.io
  dev_url: https://github.com/cuihantao/andes

extra:
  recipe-maintainers:
    - cuihantao
