{% set name = "andes" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c43e83420abf6b14c71995e4671273daeb484b21122579ed17d4221713f67f8

build:
  number: 0
  noarch: python
  entry_points:
    - andes = andes.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - kvxopt >=1.3.0.0
    - numpy
    - scipy
    - sympy >=1.6,!=1.10.0
    - pandas
    - matplotlib-base
    - openpyxl
    - xlsxwriter
    - dill
    - pathos
    - tqdm
    - pyyaml
    - coloredlogs
    - chardet
    - psutil
    - texttable
    - numba

test:
  imports:
    - andes
    - andes.core
  commands:
    - pip check
    - andes selftest
  requires:
    - pip


about:
  home: https://github.com/cuihantao/andes
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Python Software for Symbolic Power System Modeling and Numerical Analysis
  doc_url: https://andes.readthedocs.io
  dev_url: https://github.com/cuihantao/andes
  description: |
    ANDES is a Python Software for Symbolic Power System Modeling and Numerical Analysis.
    Check out the introduction in the GitHub repository and documentation.

extra:
  recipe-maintainers:
    - cuihantao
